# Topics
actual_kia_position_topic: "/gps_state"
start_topic: "/valid_path"
setpoint_topic: "/gps_setpoint"
enable_topic: "/vehicle/oscc_enable_cmd"

# path
map_path: "/home/nvidia/path_follower_ws/src/kia_map_pimot/media/mapa.png"
background_path: "/home/nvidia/path_follower_ws/src/kia_map_pimot/media/dilate.png"
path_follower_path: "/home/nvidia/path_follower_ws/src/rqt_swift_nav/sciezka.json"

# Map position
coordinate_system:
  xmin: 21.0110884233579
  xmax: 21.0190682401996
  ymin: 52.2679688744638
  ymax: 52.2701910569562
  image_size_x: 880.0
  image_size_y: 404.0
  diameter: 10
  cliced_offset: 10




