repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: poetry run isort
    types: [python]
  - id: black
    name: black
    stages: [commit]
    language: system
    entry: poetry run black .
    pass_filenames: false
  - id: pytest
    name: unit tests
    stages: [push, merge-commit]
    language: system
    entry:  pytest src
    pass_filenames: false